In [ ]:
from keras.datasets import cifar10

In [ ]:
#from keras.precessing.image import ImageDataGenerator

In [ ]:
from keras.layers import Dense,Dropout,Activation,Flatten,Conv2D,MaxPooling2D

In [ ]:
import numpy as np

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
(xtrain,ytrain),(xtest,ytest)=cifar10.load_data()

In [ ]:
xtrain.shape

(50000, 32, 32, 3)

In [ ]:
xtest.shape

(10000, 32, 32, 3)

In [ ]:
xtrain=xtrain.astype('float32')
xtest=xtest.astype('float32')

In [ ]:
xtrain /= 255

In [ ]:
xtest /=255

In [ ]:
from keras.models import Sequential
model=Sequential()

In [ ]:
model.add(Conv2D(32,(3,3),padding='same',input_shape=xtrain.shape[1:]))

In [ ]:
model.add(Activation('relu'))

In [ ]:
model.add(Conv2D(32,(3,3)))

In [ ]:
model.add(Activation('relu'))

In [ ]:
model.add(MaxPooling2D(pool_size=(2,2)))

In [ ]:
model.add(Dropout(0.25))

In [ ]:
model.add(Flatten())

In [ ]:
model.add(Dense(512))

In [ ]:
model.add(Activation('relu'))

In [ ]:
model.add(Dropout(0.5))

In [ ]:
model.add(Dense(10))

In [ ]:
model.add(Activation('softmax'))

In [ ]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics='accuracy')

In [ ]:
from keras.utils import to_categorical

In [ ]:
ytrain=to_categorical(ytrain,10)

In [ ]:
ytrain[0]

array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0.], dtype=float32)

In [ ]:
ytest=to_categorical(ytest,10)

In [ ]:
model.fit(xtrain,ytrain,batch_size=32,epochs=5)

Epoch 1/5
1563/1563 [==============================] - 257s 163ms/step - loss: 1.4132 - accuracy: 0.4932
Epoch 2/5
1563/1563 [==============================] - 233s 149ms/step - loss: 1.0751 - accuracy: 0.6216
Epoch 3/5
1563/1563 [==============================] - 230s 147ms/step - loss: 0.9316 - accuracy: 0.6702
Epoch 4/5
1563/1563 [==============================] - 216s 138ms/step - loss: 0.8300 - accuracy: 0.7079
Epoch 5/5
1563/1563 [==============================] - 212s 136ms/step - loss: 0.7455 - accuracy: 0.7378


In [ ]:
predictions=model.predict(xtest)
for i in range(5):
  print(ytest[i])
  print(predictions[i])

313/313 [==============================] - 9s 29ms/step
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[2.60902965e-03 6.00629894e-04 2.99720815e-03 8.60633433e-01
 2.50743586e-04 1.05269596e-01 7.84056634e-03 1.75190275e-03
 1.75705217e-02 4.76335321e-04]
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[1.4722848e-03 5.2338642e-01 2.0178465e-08 8.3539007e-09 4.3629064e-10
 1.4535513e-10 1.9442812e-09 4.0959723e-12 4.7422618e-01 9.1519387e-04]
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[3.3213803e-01 2.4463983e-02 3.6032822e-03 5.3738281e-03 1.7116364e-03
 3.8205652e-04 5.1295865e-05 1.7204033e-03 5.8654898e-01 4.4006616e-02]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[2.0418024e-01 7.0519693e-04 7.8480784e-03 5.3250245e-05 3.8697179e-03
 1.4498999e-06 2.2883478e-05 4.1193343e-06 7.8314096e-01 1.7408293e-04]
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[3.18491652e-06 9.01916792e-06 8.08061752e-03 3.15955095e-02
 1.50166890e-02 3.56841600e-04 9.44903851e-01 3.41678629e-06
 1.85601621e-05 1.23591835e-05]
