In [1]:
import tensorflow as tf

# Creating matrices of different shape using constant values with the help of tensorflow library.

In [2]:
X = tf.constant([1,2,3,4,5,6],shape=[3,2])
X

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [3]:
Y = tf.constant([1,2,3,4,5,6],shape=[2,3])
Y

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

# Create a 4*4 square matrix A with constant values from 1 to 16.

In [4]:
Z = tf.constant([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16],shape=[4,4])
Z

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])>

Demonstrate matrix multiplication with the help of function of tensorflow library

In [6]:
Z=tf.matmul(X,Y)
Z

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])>

In [7]:
A = tf.constant([1,2,3,4,5,6],shape=[2,3])
A

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [8]:
B = tf.constant([7,8,9,10,11,12],shape=[3,2])
B

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]])>

In [9]:
C=tf.matmul(A,B)
C

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]])>

With the help of tensorflow function create matrix using random values.

Note:- Shape,Range1,Range2,Datatype of the argument.

In [10]:
A= tf.random.uniform([2,2],minval=3,maxval=10,dtype=tf.int32)
A

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[9, 9],
       [5, 8]])>

In [11]:
B= tf.random.uniform([3,3],minval=3,maxval=10,dtype=tf.float32)
B

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[6.6225886, 5.937328 , 4.57042  ],
       [3.8652177, 9.916026 , 4.4017563],
       [3.1481276, 3.470261 , 3.4228935]], dtype=float32)>

Create a Matrix C using random values of float datatype having shape 3*2

In [12]:
C = tf.random.uniform([3,2],minval=10,maxval=50,dtype=tf.float32)
C

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[33.560062, 30.14102 ],
       [38.514893, 14.271889],
       [31.508926, 33.72686 ]], dtype=float32)>

In [13]:
eig_values,eig_vectors=tf.linalg.eigh(B)

In [14]:
eig_values

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 1.3157554,  4.2176924, 14.428066 ], dtype=float32)>

In [15]:
eig_vectors

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.39970684, -0.74785846,  0.5300401 ],
       [ 0.18280134,  0.63165945,  0.753386  ],
       [-0.89823055, -0.2042414 ,  0.3891881 ]], dtype=float32)>